Have only one CD workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -2,8 +2,12 @@ name: CD
 
 on:
   schedule:
-    # every night at midnight
-    - cron:  '0 0 * * *'
+    # Publish nightly each day at midnight UTC
+    - cron: '0 0 * * *'
+  push:
+    tags:
+      # On demand PlayStore publishing for internal testing
+      - 'internal_testing'
 
 jobs:
 
@@ -28,12 +32,14 @@ jobs:
           ndk-version: r27d
           link-to-sdk: true
 
-      - name: Decrypt files
+      - name: Retrieve secrets
         env:
           KEYSTORE: ${{ secrets.keystore }}
+          PLAYSTORE_JSON: ${{ secrets.PLAYSTORE_JSON }}
           KIWIX_FILE_UPLOAD_SSH_KEY: ${{ secrets.KIWIXANDROID_FILE_UPLOAD_KEY }}
         run: |
           echo "$KEYSTORE" | base64 -d > kiwix-android.keystore
+          echo "$PLAYSTORE_JSON" > playstore.json
           KEY_PATH=kiwix_file_upload_ssh_key
           echo "$KIWIX_FILE_UPLOAD_SSH_KEY" > $KEY_PATH
           chmod 600 $KEY_PATH
@@ -50,10 +56,37 @@ jobs:
       - name: Set date variable
         run: echo "DATE=$(echo $(date +%Y-%m-%d))" >> $GITHUB_ENV
 
-      - name: Publish to kiwix.download.org
+      - name: Publish to master.download.kiwix.org
+        if: ${{ ! github.event_name == 'push' }}
         env:
           UNIVERSAL_DEBUG_APK: app/build/outputs/apk/nightly/*universal*.apk
         run: |
           mkdir $DATE
           cp $UNIVERSAL_DEBUG_APK $DATE
           scp -P 30322 -vrp -i "$KIWIX_FILE_UPLOAD_SSH_KEY_PATH" -o StrictHostKeyChecking=no $DATE kiwix-android@master.download.kiwix.org:/data/kiwix/nightly/
+
+      - name: Publish bundle in internal testing on Google Play
+        env:
+          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
+          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
+          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
+          KIWIX_ANDROID_RELEASE_DATE: ${{ env.KIWIX_ANDROID_RELEASE_DATE }}
+        run: |
+          set +e
+          ./gradlew publishPlayStoreBundle --scan 2>&1 | tee gradle_output.log
+          EXIT_CODE=${PIPESTATUS[0]}
+          set -e
+
+          if grep -q "BUILD SUCCESSFUL" gradle_output.log; then
+            echo "Gradle build successful."
+            exit 0
+          fi
+
+          if grep -q "Try another version code." gradle_output.log; then
+            echo "Upload skipped because very same version."
+            exit 0
+          fi
+
+          echo "Gradle publish failed with an unexpected error:"
+          cat gradle_output.log
+          exit $EXIT_CODE
